apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  creationTimestamp: null
  generation: 1
  name: amq-streams
  namespace: kafka
  resourceVersion: "56398"
  selfLink: >-
    /apis/operators.coreos.com/v1alpha1/namespaces/kafka/subscriptions/amq-streams
  uid: 514c6b68-1f48-11ea-a90c-0242ac11000b
spec:
  channel: stable
  installPlanApproval: Automatic
  name: amq-streams
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  startingCSV: amqstreams.v1.3.0
status:
  catalogHealth:
    - catalogSourceRef:
        apiVersion: operators.coreos.com/v1alpha1
        kind: CatalogSource
        name: certified-operators
        namespace: openshift-marketplace
        resourceVersion: "26047"
        uid: 69d66b2e-0d43-11ea-aca5-525400baad9b
      healthy: true
      lastUpdated: "2019-12-15T14:36:45Z"
    - catalogSourceRef:
        apiVersion: operators.coreos.com/v1alpha1
        kind: CatalogSource
        name: community-operators
        namespace: openshift-marketplace
        resourceVersion: "26046"
        uid: 68399910-0d43-11ea-aca5-525400baad9b
      healthy: true
      lastUpdated: "2019-12-15T14:36:45Z"
    - catalogSourceRef:
        apiVersion: operators.coreos.com/v1alpha1
        kind: CatalogSource
        name: redhat-operators
        namespace: openshift-marketplace
        resourceVersion: "26073"
        uid: 690d9ed7-0d43-11ea-aca5-525400baad9b
      healthy: true
      lastUpdated: "2019-12-15T14:36:45Z"
  conditions:
    - lastTransitionTime: "2019-12-15T14:36:45Z"
      message: all available catalogsources are healthy
      reason: AllCatalogSourcesHealthy
      status: "False"
      type: CatalogSourcesUnhealthy
  currentCSV: amqstreams.v1.3.0
  installPlanRef:
    apiVersion: operators.coreos.com/v1alpha1
    kind: InstallPlan
    name: install-rk22s
    namespace: kafka
    resourceVersion: "56366"
    uid: 5158db6c-1f48-11ea-a90c-0242ac11000b
  installedCSV: amqstreams.v1.3.0
  installplan:
    apiVersion: operators.coreos.com/v1alpha1
    kind: InstallPlan
    name: install-rk22s
    uuid: 5158db6c-1f48-11ea-a90c-0242ac11000b
  lastUpdated: "2019-12-15T14:36:48Z"
  state: AtLatestKnown
