apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: amq-streams-operator-group
  namespace: kafka
spec:
  targetNamespaces:
    - kafka
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  creationTimestamp: null
  generation: 1
  name: amq-streams
  namespace: kafka
spec:
  channel: stable
  installPlanApproval: Automatic
  name: amq-streams
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  startingCSV: amqstreams.v1.3.0
